version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: decorator
    versions:
    - 4.4.2
    - 5.0.5
    - 5.0.6
