FROM python:2-alpine3.8
MAINTAINER Swee Tat Lim "limsweetat@spgroup.com.sg"
EXPOSE 5000 5001
ADD ./requirements.txt /sixpack/
RUN apk add build-base; \
  pip install -r /sixpack/requirements.txt
VOLUME /sixpack
ENV PYTHONPATH=/sixpack \
  SIXPACK_CONFIG=/sixpack/docker-config.yml \
  SIXPACK_PORT=5000
CMD /sixpack/bin/sixpack